### ISSUE TITLE
Google Map not loading on new IOS-Update  (IOS 10.0.1)

### ISSUE THREAD

**Issue by HartHerbert** [mapsplugin/cordova-plugin-googlemaps#1107]
I am trying to get my app that was working fine on the older ios versions to work on ios 10.
And I don't know why but when the app loads, sometimes the map loads, and sometimes not.
It's a very strange behavior and I cannot figure out how to deal with it so the map loads everytime without any problems.
would be nice if you all could give me some answers shortly, i would appreciate it

**Comment by Hirbod** [comment]
Apply this patch:
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/d5213984e88ebccd4eb031420fcdb2f50e3a784c

this should fix the problem

**Comment by HartHerbert** [comment]
I'm sorry to tell you but this wasn't the problem. I just dont get it. The api console of google notices that I made a request to load the map and count that request as done and correct but the map on my device wont show

**Comment by wf9a5m75** [comment]
Do you see the map using `map.showDialog()`?

**Comment by HartHerbert** [comment]
to be honest not. just for you to know Im using Ionic v2 with Typescript. And in android everything works just fine but in ios I just cant see the map, The map is in the second Tab in my app and if I click there just an empty square is displayed.

**Comment by wf9a5m75** [comment]
If the `map.showDialog()` does not display the map, your API key is incorrect or you forgot to enable the Google Maps SDK for iOS except you see the map on iOS9.

**Comment by HartHerbert** [comment]
look, I am the only one testing my app version on IOS and my google console api account is always displaying traffic, so that this looks like it just works fine.
![googlemaps_api](https://cloud.githubusercontent.com/assets/22191877/18649211/8e66c9a8-7ebe-11e6-8d9b-3daf5861f690.png)

if you want I can show you my log output in xcode

**Comment by wf9a5m75** [comment]
@HartHerbert It doesn't matter.

I only ask the `map.showDialog()` work or not.
We want to confirm one by one, step by step.
Otherwise, please share your whole project file with us.

**Comment by wf9a5m75** [comment]
Ok, I modified the plugin.xml for iOS10. It should work.

**Comment by HartHerbert** [comment]
ok thanks I will try it out today. Thank you for this :+1: 
Can you tell me what you changed ?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/21a461fe329f37b57f0cbf2589172af537c629c0

**Comment by HartHerbert** [comment]
ok thanks for everything by now :)
Now my map.showDialog() work.
but my map is not showing. I think its a problem with transparency..

my HTML
```
<ion-header>

  <ion-navbar app_tab_background>
    <ion-title>Karte</ion-title>
  </ion-navbar>

</ion-header>


<ion-content>

  <div id="map">

    <button fab fab-bottom fab-left class="location_button" (click)="getUserLocation();" energized>
      <ion-icon light ios="ios-locate-outline" md="md-locate"></ion-icon>
    </button>

    <ion-list>
      <ion-item class="map_header">

        <!--<div class="icon_svg">
          <img src="img/cigarettes_icon.svg">
        </div>-->
        <div item-left>
          <img id="map_img" src="">
        </div>
        <h2 id="map_title">{{map_title}}</h2>

        <p id="map_snippet">{{map_snippet}}</p>
        <ion-icon [hidden]="!navigate_possible || !gotDirections" [ngClass]="{'button-rotate':rotateIt, 'button-pulse':!rotateIt}" class="button-pulse" item-right light large ios="ios-navigate" md="md-navigate" (click)="navigateTo();"></ion-icon>
        <p class="distance_Style">{{map_distance}}</p>
      </ion-item>
    </ion-list>


  </div>

</ion-content>

```

And my .scss
```
ion-app._gmaps_cdv_ .nav-decor {
    background-color: rgba(0,0,0,0);
}



#map {
    height: 100%;
    width: 100%;
    z-index: 0;
}


.map_header{
  background-color: $app_color;
}

.distance_Style{
  color: $app_tab_background;
  font-size: large;
}

.button-pulse {
  animation: pulse 1s ease infinite;
  /* transition: transform 0.2s; */
}

.button-rotate{
  animation: roll 1s ease;
}

@keyframes roll {
  0% {
    transform: rotate(0deg);
  }

  33%{
    -webkit-transform: rotate(30deg);
    -moz-transform: rotate(30deg);
    -ms-transform: rotate(30deg);
    -o-transform: rotate(30deg);
    transform: rotate(30deg);
  }

  66%{
    -webkit-transform: rotate(-30deg);
    -moz-transform: rotate(-30deg);
    -ms-transform: rotate(-30deg);
    -o-transform: rotate(-30deg);
    transform: rotate(-30deg);
  }

  100% {
    transform: rotate(0deg);
  }
}


@keyframes pulse {
  0% {
    transform: scale(1);
  }

  50% {
    transform: scale(1.2);
  }

  100% {
    transform: scale(1);
  }
}

.location_button{
  bottom:4%;
  z-index: 200;
}

.wayTo_position{
  bottom:26%;
  z-index: 200;
}

.keep_track_position{
  bottom: 16%;
  z-index: 200;
}

.keeping_track{
  opacity:1;
  z-index: 200;
}

.not_keeping_track{
  opacity:0.4;
  z-index: 200;
}

```

Like I mentioned before, I use Ionic v2

Thanks for the help.

**Comment by Hirbod** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1007#issuecomment-231558103

**Comment by wf9a5m75** [comment]
@HartHerbert ping

**Comment by HartHerbert** [comment]
hey guys, sorry I forgot to write back.
found my answer. To be honest the answers everybody discussed in other issues here where the solution.
but I forgot that I added this to my **tabs.html** and so when I ran my app, the div that I hid was kind of in front of the map so the map displayed blank everytime. I just erased it on my IOS version and it worked great.

So for everybody to understand why I wrote this piece of code in my tabs.html:
It's only there to show the icon's on IOS as well as in Android. It was always not displaying one Icon so I did this.
So thats my solution. Thanks for everyone helping here 👍 💯 


`
<div hideWhen="ios,windows">
  <ion-tabs app_tab_background #myTabs preloadTabs="true">
    
    <ion-tab [root]="tabSearchRoot" [rootParams]="mapData" tabIcon="md-search"></ion-tab>
    <ion-tab [root]="tabMapRoot" [rootParams]="mapData" tabIcon="md-map"></ion-tab>
    <ion-tab [root]="tabAddRoot" [rootParams]="mapData" tabIcon="md-add"></ion-tab>
  </ion-tabs>
</div>

<div hideWhen="android">
  <ion-tabs app_tab_background #myTabs>
    
    <ion-tab [root]="tabSearchRoot" tabIcon="ios-search"></ion-tab>
    <ion-tab [root]="tabMapRoot" tabIcon="ios-map"></ion-tab>
    <ion-tab [root]="tabAddRoot" tabIcon="ios-add-circle"></ion-tab>
  </ion-tabs>
</div>`
