### ISSUE TITLE
Back button event conflict with registerBackButtonAction()

### ISSUE THREAD

**Issue by ryanhalley** [mapsplugin/cordova-plugin-googlemaps#1639]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.0.0-beta3-20170811-1937 "cordova-plugin-googlemaps"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

If you add the googlemaps plugin, registerBackButtonAction() will not be respected; application will exit regardless.'

**Expected behavior:**
App should continue to respect registerBackButtonAction(), and allow control of hardware back button.

**Steps to reproduce:**
1. Load project from https://github.com/ryanhalley/hardwarebackbutton
2. Run 'cordova run android -cl' and press hardware Back button on Android device; exit dialog should appear.
3. Run: ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
4. Run 'cordova run android -cl', press Back button; app will close.

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by stormwin** [comment]
+1

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/v2.0-demo/issues/49

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md#jul132017

**Comment by wf9a5m75** [comment]
So the back button is not available for you.

**Comment by ryanhalley** [comment]
Understood, many thanks.

**Comment by AndreVicenteWeb** [comment]
As I needed the back button and used the map only on one screen I opened the plugin package and commented the line document.addEventListener ("backbutton", onBackButton, false) everywhere I found it

**Comment by ryanhalley** [comment]
If I understand the change log correctly, an alternative event is being raised instead, so I should be able to replace registerBackButtonAction with this instead:
      this._events.subscribe('plugin_backbutton', () => {
        this.confirmExit();
      });

.. but no joy so far.

**Comment by wf9a5m75** [comment]
> So the back button is not available for you.

means you can not use the back button.

The backbutton is important for this plugin.
When you move back from map page or move back from another page to the map page, the map plugin have to recalculate the position and sizes of all html elements in that page.
But, there is only way is the backbutton event.

And in order to stop the program code safely when you tap on the backbutton (such as tap on the map during map.clear()), the plugin has to know the event.

For the reasons, the plugin has to know the backbutton event. So you can not use the backbutton.

-------

Even if you don't agree it, please use the another plugins, or Google Maps JavaScript API v3.

**Comment by ryanhalley** [comment]
OK, thanks for the explanation. I'm struggling to understand why this feature is so critical. I am removing the map when I leave the map page, so there is no recalculation to worry about surely?

For me personally, I have used AndreVicenteWeb's fix; the app has returned to full functionality - I can go into a map, press hardware Back, be returned to the previous page, go back in to the map, follow a link to a new page, press Back, and I'm in the map again without any issues, or be in a completely different page, press Back, and the nav works correctly (i.e like it appeared to work fine in 1.4.3 too). I'm not sure what I'm meant to be missing, but everything works correctly now, as it did before.

Perhaps you could make that event handler dependant on an environment variable, and if you set: 'dontWorryAboutHardwareBackButtonEventHandlerIfYouOnlyHaveOneMapThatYouAreRemoving' = true, because for at least two users out there, we haven't noticed any reason to lose the hardware back feature. ;)

**Comment by wf9a5m75** [comment]
Nop.

**Comment by wf9a5m75** [comment]
Did you read the code?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/googlemaps-cdv-plugin.js#L404-L421

**Comment by ryanhalley** [comment]
I've re-read your explanation yet again, and that code, and I get the issue now; I don't believe I've seen an instance where I couldn't go Back from the map, but I understand it.
Are you saying that we can have the hardware Back, if, I stop using the Cordova plugin?:
"As the uodate log describes takng care of the backbutton by this plugin is really important.
Please gve up this plugin, and use te Google Maps JavaScript v3."
If there is no way at all to have this feature, then I think I'll have to see how often our customers hit the navigation issue, to see if it is a big enough problem.

**Comment by wf9a5m75** [comment]
I'm sorry, but stoping the code safely is really important.
Everyone in the world who use this plugin taps the backbutton suddenly, even the map is still doing something.
Then the app would be crashed. After that, many people claims to me "My app is crashed!!!!".
It's really stressful for me.

**Comment by ryanhalley** [comment]
I can't argue with that. We'll monitor the situation to see if any users experience the issue enough to need a fix, and if they do, we can look into stopping using the Cordova plugin.

Thanks for bearing with me, have a great day.

**Comment by wf9a5m75** [comment]
Sorry. It is impossible to archive all person desires.

**Comment by ryanhalley** [comment]
With the hardware Back button enable workaround in place, I think was able to replicate the issue that caused you to disable the back button; I did this be entering a page, and then clicking hardware back very soon after, during the create process. After it was seen, I could not create any more maps.
To avoid this issue, so that maps create every time, AND keep the hardware back AND use the cordova v2 plugin for most of the implementation, I am using this solution:
1. commented out 'document.addEventListener("backbutton", onBackButton, false);' within all 'googlemaps-cdv-plugin.js' project instances.
It is important to remember to comment out that line, if the plugin is ever upgraded or on fresh install.
2. I took your advice, and replaced only the references to map create, marker create and their related event handlers, with javascript calls, as per your example here: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1182 (post 13 Nov 2016)

My app is now stable again, and I can aggressively create/leave map pages without issues; only if I am too aggressive (create/leave/create/leave x20 times approx in the space of 5 seconds), does the app completely crash, but this situation is not realistic for anyone to do, so I am happy with this rare corner case, because the app appears to now be (for all intents and purposes) 100% stable with v2 maps 'and' supporting the Back button; I know this is avoiding the onBackButton cleanup routine, but it is acceptable - I do wonder if using javascript for the create means there is now no need to do manual cleanup of any remaining tasks, if garbage collection can handle this.

Thank you for your various help and understanding to get me to this point.

**Comment by rafaelfl** [comment]
I have exactly the same issue. I am developing an Ionic app and when I install the plugin in the project, the hardware back button crashes the app. The log in the android debugger is something like this: 

`E/libGLESv2: HWUI Protection: wrong calling from app context F:ES2-glDeleteShader`

And there are more messages of "HWUI Protection". Any ideas of how to solve it?

**Comment by wf9a5m75** [comment]
@rafaelfl You are not exactly the same issue.
Other guys `want to use the backbutton`, but you says `your app crashes when you tap on the back button`.

You should try the latest version before asking.
`E/libGLESv2: HWUI Protection: wrong calling from app context F:ES2-glDeleteShader` is not this plugin message.

**Comment by rafaelfl** [comment]
@wf9a5m75 I have installed the 1.4 version and had no crashes. I will do some more tests.

**Comment by wf9a5m75** [comment]
The v1.4 and the v2.0-beta3 are completely different code.

**Comment by wf9a5m75** [comment]
@ryanhalley I figured out the solution, and the plugin does not block the backbutton event anymore.
Please try the new version.

**Comment by ryanhalley** [comment]
I will try today, thanks!

**Comment by ryanhalley** [comment]
OK, the Back button is now reversing out correctly, well done! but, we're not quite there yet. When you are leaving the map, the tasks are not being shutdown, which I think was your intention - this relates to the other conversation I was having with you. If you enable 'myLocationButton: true', when you enter the map, libgps can be seen in the adb logs, firing every 1 second to get the gps position. If you leave the map, this polling does not stop, the OS will announce an issue with battery drain after some time. If you recall, my hope was to split myLocationButton into myLocation and myLocationButton, so I could disable the former. For back button to be usable, we'll need to either kill all tasks when you leave the map, or avoid using specific tasks, such as gps polling, so that we can supply that data from outside the map process. I look forward to your thoughts. Well done on solving this initial Back problem, I see the fix was very short!

**Comment by ryanhalley** [comment]
I guess I don't really mean 'kill all tasks', I specifically mean 'stop the gps polling ' - that is the only issue I'm seeing that is causing battery drain, if you leave the map.
Hmm, I see that the polling continues even if I use the Navigation stack 'Back' too, so this issue isn't specifically related to the hardware Back button - it is Back in general, on Android.

**Comment by ryanhalley** [comment]
Log example, continuing after leaving map:
08-24 14:21:39.704  3646  4627 D libgps  : GpsiHook: API: gpsLocationCb(GpsiHookStateGps: e,c,G)
08-24 14:21:39.729  3646  4627 D libgps  : proxy__gnss_sv_status_cb: called. num_svs(15)
08-24 14:21:40.684  3646  4627 D libgps  : OnGpsExtensionMessage: message_id(1), data(0x727b77e044), size(2728)
08-24 14:21:40.684  3646  4627 D libgps  : GpsiHook: API: gpsLocationCb(GpsiHookStateGps: e,c,G)
08-24 14:21:40.684  3646  4627 D libgps  : proxy__gnss_sv_status_cb: called. num_svs(15)
08-24 14:21:41.705  3646  4627 D libgps  : OnGpsExtensionMessage: message_id(1), data(0x727b77e044), size(2728)
08-24 14:21:41.705  3646  4627 D libgps  : GpsiHook: API: gpsLocationCb(GpsiHookStateGps: e,c,G)
08-24 14:21:41.705  3646  4627 D libgps  : proxy__gnss_sv_status_cb: called. num_svs(15)
08-24 14:21:42.681  3646  4627 D libgps  : OnGpsExtensionMessage: message_id(1), data(0x727b77e044), size(2728)
08-24 14:21:42.681  3646  4627 D libgps  : GpsiHook: API: gpsLocationCb(GpsiHookStateGps: e,c,G)
08-24 14:21:42.682  3646  4627 D libgps  : proxy__gnss_sv_status_cb: called. num_svs(15)

This is what I should probably see, if the service had stopped, when we go Back (or part of it):
08-24 14:23:12.712  3646  3661 D libgps  : GpsiHook: API: gpsStatusCb(GpsiHookStateGps: e,c,G)
08-24 14:23:12.725  3646  3661 D libgps  : GpsiHook::deliverStatus() GPS_STATUS_SESSION_END
08-24 14:23:12.725  3646  3661 D libgps  : GpsiHook: API: gpsStatusCb(GpsiHookStateGps: E,c,G)
08-24 14:23:12.725  3646  3661 D libgps  : GpsiHookStateGps              : EXIT
08-24 14:23:12.725  3646  3661 D libgps  : GpsiHookStateIdle             : ENTRY

**Comment by wf9a5m75** [comment]
Um, it is very difficult.
The back button is used for a lot of purpose.

For example, opening a JS dialog, then close it with the backbutton(cancel the dialog), something like that.

**Comment by AndreVicenteWeb** [comment]
Thanks. For me resolves one problem.
My app shows the map in the first page and have 3 steps. When user click in button "next" the app shows step 2 and change only the html, the map continue in background. So my problem was when the user press backbutton when they are in step 2 they needed to back to step 1. Before this update when I pressed back button the map crashed, now it's not occuring anymore. 
I am having one problem: when I am in step 1 and press backbutton I close the app with this.platform.exitApp(); (ionic 2) and the app goes to background. When I open the app again they don't restart and crash, showing only a black screen. Some sugestion?

**Comment by ryanhalley** [comment]
Andre, it might be related to this, add this anyway:
    public ionViewDidLeave() {
        // If map has been created, then remove it
        if (this._map) {
            this._map.remove();
        }
    }

**Comment by AndreVicenteWeb** [comment]
Thanks @ryanhalley .
I tested in ionViewDidLeave, tested before call this.platform.exitApp(), tested this._map.remove() wait 2 seconds and after exit. Always crash the app. I did this tests with this last version now.

**Comment by ryanhalley** [comment]
I suspect you don't have registerBackButtonAction() configured within app.component.ts (please google an example for the related tryAndGoBack code), so that exitApp can/should occur there.

**Comment by ryanhalley** [comment]
Wait, no, you are right. I am seeing the same issue now. Black screen after I restart the app.

**Comment by AndreVicenteWeb** [comment]
I was using exitApp inside a page, now I changed to app.component.ts , same thing.

**Comment by AndreVicenteWeb** [comment]
This bug doesn't happens when the location is turned off

**Comment by wf9a5m75** [comment]
@AndreVicenteWeb Please share your project files on github or bitbucket.
(Or create demo project)

**Comment by wf9a5m75** [comment]
![issue1639](https://user-images.githubusercontent.com/167831/29685633-e6ba4028-88ca-11e7-9a1a-a8c563163d89.gif)

I have an ionic code for cluster test fortunately, I tested the code.
But I can not reproduce the issue.

```
    platform.ready().then(() => {
      platform.registerBackButtonAction(() => {
        alert("see you");
        platform.exitApp();
      });
      //this.loadMap();
    });
  }
  ionViewDidEnter() {
    var self = this;
    setTimeout(self.loadMap.bind(self), 1000);
  }
  ionViewDidLeave() {
    // If map has been created, then remove it
    if (this.map) {
      this.map.remove();
    }
  }
```

**Comment by ryanhalley** [comment]
Thanks, I'm also building a test case to try and replicate.

**Comment by CesarAPPinheiro** [comment]
Great new that the backbutton is working now @wf9a5m75 !
 I found a bug with the map.
When I push a page to load and go back to the root where my map is the map get streched and only goes back to normal after I click on the map screen.

Is there any way to fix it ?

**Comment by wf9a5m75** [comment]
@CesarAPPinheiro I don't know which version do you use, but it's easy.
When you enter(?) to the map page,  execute `cordova.fireDocumentEvent('plugin_touch', {});`

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/whats-new-v2/README.md#change-4-save-battery-life

**Comment by ryanhalley** [comment]
Hi, sorry to reuse an old repository, but here's the testcase: https://github.com/ryanhalley/googlemapsiconurl

If you have 1 icon on the map, you can back out of the app and reopen it ok. libgps service stops ok.
If you add 100 icons, the issue will appear.

**Comment by wf9a5m75** [comment]
@ryanhalley Thank you for creating demo app.
I fixed the bug. Please reinstall the plugin.
The map stops the GPS correctly when you remove the map.

**Comment by ryanhalley** [comment]
That's great news, well done! Testing now.

**Comment by ryanhalley** [comment]
Yep, I think you've cracked it. I tried to break it with myLocationButton enabled by rapidly entering/leaving the page - only once did I appear to beat the service shutting down correctly, but a second or so later, it did shut down nicely. After all that back and forth, I then backed out of the app, and re-entered without any issues.
There is a bug remaining though. During the same session as above, I just entered the map and pressed the mylocation button for the first time (with the one hundred icons on the screen in the example) - the map moved to my location, and I see map tiles only on the left hand 50% of the screen (exactly), and blank on the right half (where the my location blip appears). I've moved the map a little to the right, and it is not resolving the issue.

**Comment by ryanhalley** [comment]
Same instance still - I've left/reentered the page to see if it is a one-off, and I see the map tiles at my start position, but when I press the button I now don't see any tiles at my location, I can't seem to get the map to update at all.

**Comment by ryanhalley** [comment]
Hmm, ok, the issue is easier to reproduce. I quit the app entirely, and restarted fresh (ionic cordova run android -cl). I went to the map page, saw the icons load, then clicked the button - sent to my location, and no map tiles loaded.

**Comment by AndreVicenteWeb** [comment]
Sorry about yesterday, I had to leave.
THANKS, NOW IT'S WORKING WELL. The problem for me was resolved 100%.

**Comment by ryanhalley** [comment]
I uninstalled plugin and reinstalled it - problem is gone; I suspect it was related to the API key in some way. I'll close the ticket, many thanks for this breakthrough.
