### ISSUE TITLE
Plugin dont add all markers with custom icons to map with latest commit

### ISSUE THREAD

**Issue by lpikora** [mapsplugin/cordova-plugin-googlemaps#1684]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[x] **Android**
[ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.0-beta3-20170820-2025 "cordova-plugin-googlemaps"
cordova-plugin-ios-camera-permissions 1.1.1 "iOS Permissions"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
When adding multiple markers, plugin do not add all markers. It seems that somehow fail in the middle of adding markers. Some markers appear but not all. Fail is in commit 2ca25c7e52dc333bf994831c36dd9ad3619f6fe3. Commit 8cfad6468c131e95264dad177cb29b78a9ab7d39 works ok.

Unfortunatelly no error in logcat appears.

**Expected behavior:**
Add all markes in map.

**Steps to reproduce:**
Add multiple markers with custom icons encoded in data url.

**Comment by ryanhalley** [comment]
Your googlemaps plugin is over a week old, worth trying the latest.

**Comment by wf9a5m75** [comment]
The version `2.0.0-beta3-20170820-2025` is too old. please try the latest version at least.

Even if the issue is not solved, please share your project files on github, or create a demo project then share it on github.

**Comment by lpikora** [comment]
Im sorry i ran `cordova plugin list` in different directory. I found this bug in this specific commit 2ca25c7e52dc333bf994831c36dd9ad3619f6fe3 as I described. Previous commit is ok.

**Comment by wf9a5m75** [comment]
please share your project files on github, or create a demo project then share it on github.

**Comment by lpikora** [comment]
Hi, I created example https://github.com/lpikora/cluster_test

commit 8cfad6468c131e95264dad177cb29b78a9ab7d39 works well,
but e5f244013f862e4062822a9791d3fe285ea8e442 do not add all markers on map.

my setup:

```
cordova 7.0.1
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-googlemaps 2.0.0-beta3-20170829-1218 "cordova-plugin-googlemaps"
cordova-plugin-whitelist 1.3.2 "Whitelist"

Android 7.1.1
```

**Comment by wf9a5m75** [comment]
This is also fixed in https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1692

**Comment by lpikora** [comment]
Sorry, but i cant confirm this issue is fixed in b7b011a41ad5138ba81a75e3fb58f57c5aaff957. Intalling this commit in https://github.com/lpikora/cluster_test does not help...

https://gfycat.com/gifs/detail/filthyuncomfortablealpineroadguidetigerbeetle

**Comment by wf9a5m75** [comment]
Did you reinstall the latest version?

**Comment by wf9a5m75** [comment]
![1684](https://user-images.githubusercontent.com/167831/29898253-9f12f49e-8d99-11e7-802e-7dda0fd56213.gif)

**Comment by lpikora** [comment]
I think yes. Latest commit b7b011a41ad5138ba81a75e3fb58f57c5aaff957. https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1692 is fixed now. But it seems clustering (adding markers to map) is not fixed for my testing device / setup. https://gfycat.com/gifs/detail/affectionatedeargreatdane

I have updated https://github.com/lpikora/cluster_test

my plugins directory package.json has the same resolved git commit as your latest commit:
`"_resolved": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#b7b011a41ad5138ba81a75e3fb58f57c5aaff957",`

**Comment by wf9a5m75** [comment]
I have a question.
You specify `boundsDraw: true`, but why the red rectangle is not drawn in your screen record.
I think you test different code.

**Comment by wf9a5m75** [comment]
By the way, specifying the commit ID does not make sense.
I updated couple of times in a day almost everyday, so specifying the multiple_maps is fine.

**Comment by wf9a5m75** [comment]
Ah, I got the reason.
I certainly fixed this issue, but I missed to copy the code from your app to the repo folder.
That's why.
I will update the repo soon.

**Comment by wf9a5m75** [comment]
The bug is finally fixed.
![1684](https://user-images.githubusercontent.com/167831/29902033-76d3e67a-8db0-11e7-8002-6f9d73be8b7f.gif)
