### ISSUE TITLE
MultipleMap branch: Opening QR scanner freeze the app

### ISSUE THREAD

**Issue by vosecek** [mapsplugin/cordova-plugin-googlemaps#1949]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x] any problem or bug report
[ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[x] **iOS**

**cordova information:**
```
branch-cordova-sdk 2.6.17 "branch-cordova-sdk"
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-qrscanner 2.5.0 "QRScanner"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-swift-support 3.1.1 "SwiftSupport"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**
Using QR scanner (https://github.com/bitpay/cordova-plugin-qrscanner) in combination with MultipleMap branch (ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps) "freeze" the app once the scanner is opened, even if is closed and destroyed by QRScanner.destroy() the HTML elements (in map and even the menu button and header bar buttons) are not clickable.

The problem is only in iOS, works properly with Android.

Stable branch works, I am little bit worried by another upgrade of stable branch.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub if you want to check it by me.

**Comment by wf9a5m75** [comment]
ping

**Comment by vosecek** [comment]
example: https://github.com/vosecek/map-qr-problem

Map is not visible after modal closed, do not know why, but in my real project with #multiple_maps it is ok.

**Comment by wf9a5m75** [comment]
Thanks. I saw your code. Try the multiple_maps branch version

**Comment by wf9a5m75** [comment]
Well, I tested your repo, but even map is not created, the dialog box can not touch at all.

**Comment by vosecek** [comment]
Map is not created due to incorrect combination app id and key for maps you used.
Missing map content is not connected with unclickable content after qr scanner initialization with multiple_maps branch.

**Comment by wf9a5m75** [comment]
I changed the api key of course. Unfortunately, it seems this is not plugin's problem. Please ask to the QR code plugin developer.

**Comment by vosecek** [comment]
I hope that master branch will work in future, because it works now, but the same version of qr-scanner and #multiple_maps branch breaks the app.

**Comment by wf9a5m75** [comment]
I see. I will inspect more details.

**Comment by wf9a5m75** [comment]
Okay, I inspected this more deeply, and I fixed one bug, but the QRscanner plugin has also another bug.

**Can not touch the close button on the header** is this plugin bug.
I fixed it. Please reinstall the maps plugin from the `multiple_maps` branch.

```
$> git clone https://github.com/mapsplugin/cordova-plugin-googlemaps

$> git checkout multiple_maps

$> git pull

$> cd (project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add (path to)/cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." 
```

And you don't need to execute the `plugin_touch` at all.

-------------

However after closing the camera, the map is gone.
**Actually, the map is still stay at the same location, but the QR scanner plugin hides the map.**
This is not this plugin bug. You need to contact to the QR scanner plugin developer.

![screen shot 2017-12-27 at 3 37 05 pm](https://user-images.githubusercontent.com/167831/34396291-a05444e8-eb1d-11e7-80e3-820d0f0f169d.png)


![1949](https://user-images.githubusercontent.com/167831/34396310-ebbb45e4-eb1d-11e7-9594-f562139dae1c.gif)

**Comment by wf9a5m75** [comment]
Since this is already fixed at this plugin side, I close this thread. But you can still reply to this thread.

**Comment by vosecek** [comment]
Thanks, there is another problem with combination this plugins described here: https://github.com/bitpay/cordova-plugin-qrscanner/issues/120, can be easily solved by updating plugin code.

The white screen problem remains in #multiple_maps branch on close even with qr-plugin code update described above. I found a simple patch: creating new instance of LoadingController, showing and hiding it immediately on QR Camera close. After this the map is showed properly.
